#!/bin/sh -e

pluginpath='/usr/lib/nagios/plugins'

if [ ! -f $pluginpath/shd/check_esx ]; then
  ln -s $pluginpath/check_esx $pluginpath/shd/check_esx
fi
if [ ! -f $pluginpath/shd/snmp_bulk ]; then
  ln -s $pluginpath/check_snmp_bulk $pluginpath/shd/check_snmp_bulk
fi
if [ ! -f $pluginpath/shd/check_top ]; then
  ln -s $pluginpath/check_top $pluginpath/shd/check_top
fi
if [ ! -f $pluginpath/shd/check_xen.py ]; then
  ln -s $pluginpath/check_xen.py $pluginpath/shd/check_xen.py
fi

#templdir=/usr/share/nagios-plugins/templates-shd
#npconfdir=/etc/nagios-plugins/config

#if [ "$1" = "configure" ]; then
#	(
#		cd $templdir
#		for f in *cfg; do
#			dest=${npconfdir}/$f
#			ucf $f $dest
#		done
#	);
#fi

