#!/bin/sh -e



#templdir=/usr/share/nagios-plugins/templates-shd
#npconfdir=/etc/nagios-plugins/config

#if [ "$1" = "configure" ]; then
#	(
#		cd $templdir
#		for f in *cfg; do
#			dest=${npconfdir}/$f
#			ucf $f $dest
#		done
#	);
#fi

