#!/bin/sh -e

SHD_PLUGINS="check_xen_shd.py check_share_fuse_shd.py"

if [ "$1" = "purge" ]; then
	if which ucf >/dev/null 2>&1; then
		have_ucf="yes"
	fi
	for f in $SHD_PLUGINS; do
		rm -f /etc/nagios-plugins/config/${f}.cfg
		if [ "$have_ucf" = "yes" ]; then
			ucf --purge /etc/nagios-plugins/config/${f}.cfg
		fi
	done
fi
